version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=motorist
  mailcrab:
      image: marlonb/mailcrab:latest
      ports:
      - '1080:1080'
      - '1025:1025'
      networks: [default]