version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 7654:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=motorist-manufacturer-db
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
